apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: modelregistry-sample
spec:
  postgres:
    sslMode: verify-full
    sslRootCertificateConfigMap:
      name: model-registry-db-credential
      key: ca.crt
